---
name: nginx

services:
  nginx:
    image: nginx:1.26.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/core.d:/etc/nginx/core.d
      - ./conf/ssl.d:/etc/nginx/ssl.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./data:/data
  go-httpbin:
    image: atompi/go-httpbin:v2.12.0
    restart: always
    env_file: ./go-httpbin.env
  webhook-tester:
    image: tarampampam/webhook-tester:1.1.0
    restart: unless-stopped
    command: serve --port 8080 --create-session 00000000-0000-0000-0000-000000000000

networks:
  default:
    external: true
    name: compose
